### ISSUE TITLE
Explanation of templated/value unclear

### ISSUE THREAD

**Issue by dschulten** [mamund/hal-forms#11]
I do not understand how to use templated property values.

>   * +templated+ : Indicate whether the +value+ element contains a https://tools.ietf.org/html/rfc6570[URITemplate] string for the client to resolve. This is a valid JSON boolean. This is an OPTIONAL element. If this element is missing, set to empty, or contains unrecognized content, it SHOULD be treated as if the value of +templated+ is set to `false'.

Example:

``` javascript
"_templates" : {
  "default" : {
      "title" : "Create",
      "method" : "post",
      "contentType" : "application/json",
      "properties" : [ {
         "name" : "widget", 
         "value" : "http://example.com/{foo}/path/{?bar*}", 
         "templated" : true
      }]
```
Is the idea to send a URL to the server?

Ah - afterthought: maybe the value can be exactly one template variable:

``` javascript
"_templates" : {
  "default" : {
      "title" : "Create",
      "method" : "post",
      "contentType" : "application/json",
      "properties" : [ {
         "name" : "wassacominago", 
         "value" : "{bar*}", 
         "templated" : true
      }]
```
So, if the client had a list of wassacominago, 

```
var wassacominago= ["bar1", "bar2", "bar3"]
```
it would construct

`wassacominago=bar1,bar2,bar3`

Is that what it's for?

**Comment by mamund** [comment]
yes - you get the idea. HAL-FORMS uses the URITemplate spec to make it possible to resolve scalar values, not just URIs.

**Comment by dschulten** [comment]
Suggestion, because the current wording led me to believe that templated is mainly for sending URLs to the server:

+templated+ : Indicate whether the +value+ element is a string containing https://tools.ietf.org/html/rfc6570[URITemplate] variable expressions for the client to resolve. This is a valid JSON boolean. This is an OPTIONAL element. If this element is missing, set to empty, or contains unrecognized content, it SHOULD be treated as if the value of +templated+ is set to `false'.

Is the underlying motivation the case where the property name to be sent is different from the identifier by which a matching value is known to server and client? Otherwise the property name would be sufficient.

**Comment by mamund** [comment]
yes, that's one reason to use it -- 

using the URITemplates engine allows servers to describe cases where clients should:
- supply values when the local property names are not the same as thestate-transfer names (e.g. `"search-value" : "{itemTitle}"`)
- combine multiple local property values into a single state-transfer value (e.g. `"fullname" : "{familyName}, {givenName}"`
- describe cases where multiple local property values can be supplied for a single state-transfer value (e.g. `"color-preferences" : "{*colors}"`)

there may be others, too.

in general, leveraging a resolution engine like URITemplates provides quite a bit of future-proofing and allows both client and server developers some creative options without too much work on the part of designers or implementers.

**Comment by mamund** [comment]
@dschulten 

your content suggestions works for me. feel free to work up a PR for it and i'll merge it in.
