### ISSUE TITLE
New property "multi" for fields that allow multiple selection

### ISSUE THREAD

**Issue by anderruiz** [mamund/hal-forms#17]
Include a new optional property "multi" for those fields that allow multiple selection (usually Suggests)

Example:

```
      {
        "name": "options",
        "value": "[]",
        "multi": true,
        "suggest": [
           {"value":"DAY_TRANSFER", "prompt":"day transfer"}, 
           {"value":"RECOVERABLE", "prompt":"recoverable"}, 
           {"value":"NOTIFIABLE","prompt":"notifiable"}
        ]
      }
```

**Comment by dschulten** [comment]
should it be
```
"value" : []
```
Where the items are zero or more "value" attributes from the suggest array?

**Comment by mamund** [comment]
see #24 for more on the `suggest` construct. we should add `multi` as a property of `suggest`
