### ISSUE TITLE
add support for a render property to give hints on how to render the content

### ISSUE THREAD

**Issue by anderruiz** [mamund/hal-forms#18]
As you already Suggested adding an optional field "RENDER" could help human-facing apps, as it provides hints on how to render the content. This is something we are missing, as we are starting to develop real apps. We should provide the possible values of the RENDER field. 

i.e
- select
- multiSelect
- radio
- suggest (autosearchable)
- text
- number
- hidden
- color
- date
- datetime
- email
- telephone
- time
- range (slider)
- url
- password
- ...

**Comment by mamund** [comment]
covered in #36
