### ISSUE TITLE
Is _templates.property.value really a JSON string?

### ISSUE THREAD

**Issue by dschulten** [mamund/hal-forms#20]
The spec says about `_templates.property.value`:

> value : The parameter value. This is a valid JSON string

In line with this, the example hal-forms response has:

```
 "properties" : [
    {...},
    {
      "name" : "completed", 
      "required" : false, 
      "value" : "false",          <-- JSON string 
    }
]
```

However, in the example app/json request the value is a JSON boolean:

```
{
  "title" : "A Sample HAL Forms Response",
  "completed" : false          <-- boolean
}
```

Which one is correct? If both, how would the client know to convert the string to a boolean? My feeling is, `_templates property.value` should be a JSON scalar.

**Comment by mamund** [comment]
now see #36 for more discussion on implememtation details to sort this out.
