### ISSUE TITLE
Considered json-schema?

### ISSUE THREAD

**Issue by evert** [mamund/hal-forms#23]
I'm currently implementing a REST api based on HAL. A big part of this is that we're serving both:

* HAL
* HTML

The HTML output is actually rendered by doing an internal request for HAL, and taking out the links, properties, etc. So it really kind of ends up being something like a HAL client, but built straight into the api itself.

The big thing I'd love to think about next is indeed forms. I have a few different ways I'm thinking about this. One of the ways is to actually just produce HTML forms statically on a case-by-case basis.

What I'd actually really like to do is make form-generation also an integral part of the API. HAL-FORMS might allow me to do this, but the big thing I'm missing is json-schema integration.

We're using json-schema for all our document-structure validation and provide links to it via a `describedBy` relation type. If HAL forms supported it, I could straight up embed my json-schemas in a HAL-forms object and generate quite complex interfaces.

Right now I could potentially just try to map our json-schema to HAL-Forms, but it's a bit more minimal which means that it will be a bit of a lossy transformation and only the simplest schemas can be turned into forms.

So my question really is: have you ever considered doing this, or do you see reasons why it would be a mistake?

Thanks,
Evert

**Comment by mamund** [comment]
my first response is: sure, you can add json-schema support to HAL-FORMS as long as it doesn't break anything in the current spec. 

my second response is: how it is you are using json-schema today? and what does it offer that the current HAL-FORMS spec doesn't? 

finally, if you want to move ahead with a forward/backward-compatible mod that includes json-schema, feel free to propose one. i suspect you just need another `_link` property (`"describedBy" : { "href" : "..."}` within the returned HAL-FORM, right? or did you have something else in mind?

**Comment by evert** [comment]
Yea my thinking was to do something like Hal forms, but in place of 'properties', use a JSON schema.

The problem with using properties (for me at least) is that it's not sufficient to construct our entire media types on the fly, which use things like arrays and objects.

The way I read HAL forms is that we're basically limited to a flat list of properties. So my thought was indeed, have you ever thought of JSON schema fully in place of the ’properties’ object?

**Comment by mamund** [comment]
yes, HAL-FORMS is meant to convey the input properties as a list. it need not be "flat", tho:

```
{
  {"name" : "address", ...},
  {"name" : "address.street", ..},
  {"name" : "address.city",...},
  {"name" : "address.state",...},
  {"name" : "address.postalCode",...},
}
```
can be interpreted as 
```
{"address" : {
  "street" : "...",
  "city" : "...",
  "state" : "...",
  "postalCode" : "..."
  }
}
```
and so forth...

given your explanation, i suspect you want to do something like this:

```
{
  "_links" : {
     "self" : {
      "href" : "http://api.example.org/rels/create"
    },
     "describedBy" : {
       "href" : "http://schema.example.org/create"
    }
 },
  "_templates" : {
    "default" : {
      "title" : "Create",
      "method" : "post",
      "contentType" : "application/json"
    }
  }
}
```
which would be seen as a non-backward-compatible mod since existing HAL-FORMS clients would not be able to:
1) understand the "describedBy" link
2) find any properties to pass and thus would always send an empty body (or no URL args)

this might not be what you have in mind, tho. 

can you show an example that would be backward-compatible for exsiting HAL-FORMS clients?

**Comment by evert** [comment]
Hi!

So a bit more info. The reason I submitted this ticket was to actually suggest changing HAL-FORMS to use the standard json-schema. I never intended to suggest a backwards-compatible change ;) Since it's still a draft, I figured this is a good time to bring up some ideas, and I also just wanted to see how you felt about it, or where the pitfalls might be.

Aside: `describedBy` is probably not a good relation type in this case, as that should actually 'describe' the HAL forms syntax, not the actual enclosed form.

What you describe with nested properties makes sense and solves a tiny bit of our use-case. Our actual schemas are much more complex though. Here's another (simple) example of something I might want to describe with HAL forms. In hypothetical example we have a blog post that has a series of tags, each are a simple string:

```js
{
  _links  : {
    self: { href: '/article/5' },
    describedBy: { href: 'http://example.org/schemas/blogpost.js', type: 'application/schema+json' }
  },
  title: "Hello world",
  tags: ["foo", "bar"]
}
```

The associated (partial) schema for this looks a bit like this:

```js
{
  '$schema': 'http://json-schema.org/schema#',
  '$id' : 'http://example.org/schemas/blogpost.js',
  type: 'object',
  required: ['title', 'tags'],
  properties: {
    title : {
      type : 'string',
      maxLength: 255,
   },
   tags: {
     type: 'array',
     items: {
       type: 'string'
     }
  }
}
```

Here's an example that (afaik) cannot be easily expressed with HAL-forms: an array of strings. My (ideal) end goal is to add 'forms' support to our HAL-based API (no pun intended) and re-use our existing media types, instead of creating specialized ones.

**Comment by mamund** [comment]
understood.

sounds like you have a pretty clear idea of what you want in a "forms spec" for HAL. 

i don't have any plans to change the basics of HAL-FORMS to remove the existing `properties` approach. i suspect your idea of a schema-based form spec would get some good traction and, AFAIK, there is no existing form spec for HAL like this. 

i encourage you to start a new spec and wish you all the best.

**Comment by evert** [comment]
Frankly, I'm not even really sure if this can work ;) just wanted to hear your thoughts about it. Sounds pretty clear that that you're not interested though, and that's cool too.

I'm still a bit on the fence and might still go for hal-forms. It is a lot simpler

**Comment by mamund** [comment]
@evert 

FWIW, i would definitely build an implementation for the schema-forms thing just to see what it would really take. you never know. 

also, there are some interesting possibilities if you combine the json-schema w/ json-patch and/or merge-patch, too. i've been thinking about designing a "forms" spec that relies almost exclusively on patch<G>.

in the mean time, feel free to continue to contribute ideas to help improve HAL-FORMS. always interested in additional feedback/ideas.

**Comment by evert** [comment]
For now I've decided to go straight up with HAL-FORMS. ;) Maybe I'll get back to this one day if the need arises. Having this discussion did help me think about the problem more deeply so it definitely was helpful. Thanks!

**Comment by mamund** [comment]
@evert : 
sounds good. looking forward to your comments/feedback as you start to use HAL-FORMS in real settings.
