### ISSUE TITLE
Open spec up to support multiple links - don't confine to "self"

### ISSUE THREAD

**Issue by gregturn** [mamund/hal-forms#25]
> For this release, the only valid value for the key element is "self".

This part of the spec indicates that HAL-FORMS documents are only allowed to have one link.

To be backwards compatible, I think it would make sense to support multiple links. Or at least be optional.

If we could just tweak things so that it clearly states that templates operate on the "self" link.

**Comment by mamund** [comment]
I'm going to close this one (ref: "self") and we can continue the work on #24
