### ISSUE TITLE
Add support for data type to properties

### ISSUE THREAD

**Issue by colin-young** [mamund/hal-forms#27]
Similar to #6, but instead of focusing on the presentation, I'd like to be able to specify the type of data expected in a field. From that a client could determine how best to present it. e.g. if the type is `Date` a date picker could be presented, or, to borrow another example from #6, `email` would hint to the client that on a mobile device the user should be presented with the email keyboard.

However, I'd like to go a step further and suggest json-ld, although I'm fairly certain that it wouldn't require explicit support (unlike #23 proposed for json-Schema). As an example, I have an API that requires an address, which is a nested object and being able to specify e.g. `"dataType": "@context: http://schema.org/Address"` which would allow me to build intelligent clients that would know to find the component that knows how to render that particular schema. I _think_ this can be achieved with a simple extension to the properties with a simple new optional property (I'm about to try that).

I'm curious why data type is not already included? It seems simple and obvious, which means I'm probably not considering something.

**Comment by mamund** [comment]
covered in #36
