### ISSUE TITLE
Expand `contentType` to support other media types

### ISSUE THREAD

**Issue by gregturn** [mamund/hal-forms#30]
Can we lift the restriction on `contentType` and let it support, well, any media type?

People are wanting to create REST endpoints with Spring HATEAOS that can receive `application/hal+json` on a PUT, and wondering why they can't put that in their HAL-FORMS documents under `contentType`.

**Comment by mamund** [comment]
made some changes to support opening up the media-type values for `contentType` property. 

feedback welcome.

**Comment by gregturn** [comment]
Looks great.

**Comment by gregturn** [comment]
@mamund Do you need to either A) move https://rwcbook.github.io/hal-forms/ to be based off this repo, or B) sync the two?

**Comment by mamund** [comment]
Working on resolving the forks now.

Should be cleaned up shortly.

Thanks.

**Comment by gregturn** [comment]
Seeing this change in the spec, I am closing this issues as resolved. Thanks @mamund!
