### ISSUE TITLE
support HTML5 types for inputs

### ISSUE THREAD

**Issue by mamund** [mamund/hal-forms#36]
(per @evert in #34)

"Support for a type property in each field, maybe just referencing the HTML5 specification for it's possible values. Also mentioned in #6. It might be helpful to mention what each 'type' serializes to. For example, a checkbox will probably generate a JSON boolean."

**Comment by mamund** [comment]
@evert:

i've updated the spec with the OPTIONAL `type` support for the following inputs types:

NEW TYPE VALUES
`hidden`, `text`, `search`, `tel`, `url`, `email`, `password`, `date`, `month`, `week`, `time`, `datetime-local`, `number`, `range`, `color`.

NOT FILE
note that `file` is not listed here because it takes some additional processing by _clients_ that needs to be documented. I have at least one version of that created for CollectionJSON and there are others that might be better. We can make that a separate issue, if you want support for uploading files.

NOT CHECKBOX, RADIO
also, while `radio` and `checkbox` are in this list of supported `types`, i think they will be better supported using the same construct that i have planned for SELECT-OPTIONS. I wil be borrowing the `suggest` element from my WESTL spec (http://rwcbook.github.io/wstl-spec/#_suggest_arrays) and expanding upon it to support `options`, `radio`, and `checkbox`. more on this as i work through some details.

let me know what you think.

**Comment by evert** [comment]
This sounds great. I definitely understand the rationale. One approach for `file` might be to just leave the serialization undefined for application/json, but explicitly do define it for `multipart/form-data`, but not sure if that's too much of a scope change for you.

I'm not very interested in a file-in-json serialization, but it's nice to be able to allow people to upload files. Similarly I've been thinking if there's a way to tell a client to just do a `PUT` request with for example a straight up `image/png`. A common use-case for me, but since everything wants 'fields' or 'properties', I haven't seen an obvious way to express this with any format.

Anyway, I think I went off-topic. Thumbs up from me

**Comment by evert** [comment]
A few more thoughts:

Does it make sense to limit the appearance of `min`, `max`, `minLength`, `maxLength`, `step` based on the `type`?

Have you thought about how types will map to JSON? Many are obvious, but it might be helpful to point out specifically that `type: 'number'`, implies that the serialized value is a JSON number.

What would hidden be? My guess is `boolean | number | string`. What about date serializations?

HTML doesn't have to make several of these decisions since theres no types in urlencoded form submissions.

**Comment by evert** [comment]
There _might_ be prior art here, but I couldn't find it on a first skim: https://www.w3.org/TR/html-json-forms

**Comment by mamund** [comment]
@evert:
FILE UPLOAD
file upload details in html0-json-forms is pretty straight-forward (better than multipart-data!). thanks.

i was not a fan of html-json-forms since it relied on smuggling all the important info in the `name` property (makes it non-transferable w/ form-urlencoding). but there might still be some good stuff in there.

SERIALIZATION 
mapping value types to JSON is, IMO, not ideal but i know it's common. HTML was *smart* to makek all serialized values strings -- keeps the Postel quotient high. strong-typing in responses increases the chances of errors and decreases the chances of acceptances (low Posetl quotient). My suggestion would be to use _"the value SHOULD serialized as boolean but MAY be serialized as string"_ or something similar. that allows clients to enforce strong typing (and reject failures) if they wish but not require it.

what would help me alot is you providing the serialization maps for these input types. you're closer to the work than I am and i'd be happy to accept your experience as a guide.

feel free to just plop it in this thread, if you like and I'll fold it into the spec.

BTW - as the `property` definition in the spec is getting pretty long, i plan to re-org the document and break out the attributes in a separate section w/ a reference in the main properties listing. should improve readability and maintainability, too.

**Comment by evert** [comment]
This was my take:

* `color` - string. I don't do any validation here, so I basically accept anything. I assume it's usually #RGB, #RGBA, #RRGGBB or #RRGGBBAA.
* `date` - string, `YYYY-MM-DD`. Supports min, max, step.
* `datetime-local` -  `YYYY-MM-DDhh:mm:ss`. No timetimezone. Supports min, max, step. Might(?) also support milliseconds. 
* `email` - string
* `hidden`. I had this as string, but in hindsight this should probably be 'any'.
* `number` - number
* `month` - string, `YYYY-MM`.
* `password` - `string`
* `radio` - I model this similarly to select-options.
* `range`- This is really just a number but with a diffent UI control in HTML5
* `search` - string
* `tel` - string
* `time` - string. has min, max, step 
* `url` - string
* `week` - string. `2020-W51`. has min, max, step

**Comment by mamund** [comment]
> hidden can be scalar. ??

i see the "supports" pattern here, too. we can weave that in. 

and yes, most are strings. there will be some issues for the `select-options` for value vs. text. we can deal with that later.

some types "beg" for optional client-side validation (email, & url).  date/time is a mess<g>. are the W51, etc. bits from HTML5? i'll scan the HTML5 docs to see what's there. 

no booleans here right now (huh).

FWIW, HAL-FORMS supports `regex` (instead of HTML5 `pattern`) and that can handle things like min/max, length, etc. now that we're adding them, some hierarchy will need to be called out (if both appear, use min first, then regex, etc.)

and yes, radio will be part of the select-options colleciton, good catch. 

i'll do a deeper review and update the spec in the next few days. feel free to return and tweak as you wish.

**Comment by evert** [comment]
> FWIW, HAL-FORMS supports regex (instead of HTML5 pattern) and that can handle things like min/max, length, etc. now that we're adding them, some hierarchy will need to be called out (if both appear, use min first, then regex, etc.)

Since these conditions are basically a logical AND, does order matter? I think UI's will want to use min/max for better feedback in case of validation errors, but not sure this is something that has to be addressed in the spec.

**Comment by mamund** [comment]
> Since these conditions are basically a logical AND

it matters if the two are on confict and/or one of them is in error.  

and, yes, human interfaces will do better with min/max, etc. machines can do quite well with expressions.

we can support both.

**Comment by mamund** [comment]
@evert 

to keep things simple for this document (and in sync w/ HTML) i've added the following line to the `type`attribute definition:

> For hints on how to render and process various type values as well as for guidance on how each type value affects to the contents of the associated value property, see [https://www.w3.org/TR/html52/sec-forms.html#element-attrdef-input-type].

This good enough for now?

**Comment by evert** [comment]
Nice! Sounds good!

**Comment by mamund** [comment]
cool. i'll be sure to clean up the grammar and then we can move on to the SELECT...OPTION ("suggest") control description to close out this round of issues for the spec.

cheers.
