### ISSUE TITLE
support additional input qualities (ala HTML5)

### ISSUE THREAD

**Issue by mamund** [mamund/hal-forms#37]
(per @evert in #34)

"Support for placeholder, min, max, step, minLength, maxLength"

**Comment by evert** [comment]
I saw the work done on this, great!

In my implementation I'm going to assume that `type=number` if step/min/max appears, otherwise I'll default to `text`.

**Comment by mamund** [comment]
@evert : good point, when i add the `type` support i'll update the docs for step/min/max, too.

thanks.

**Comment by evert** [comment]
Not sure if this is interesting, but `hal-types` has been updated with these changes https://github.com/evert/hal-types#readme

Ketting will follow a little later.
