### ISSUE TITLE
Lookup properties with `type=uri`

### ISSUE THREAD

**Issue by evert** [mamund/hal-forms#48]
At the risk of asking for too much...

We use links for relationships. It's not unusual therefore for a user to select a related resource for something they are editing,
For example, a user is writing a blog article. One of the fields is a 'category'. Categories are expressed as link relationships and are separate resources.

It would be really nice if we can point a property to a 'category' collection, fetch a list of categories and use it to populate a `<select>` field. We have a couple of heuristics for determining the title for any given resource.

**Comment by mamund** [comment]
actually, the "suggest" pattern has that built in<g>.

essentially, you'll be able to have a list inline, a list ref'd in the existing doc, and a URL ethat returns name/value pairs.

i run into your use case *all the time* in both human and machine cases.

hopefully, what i have in mind will work for you.

**Comment by mamund** [comment]
closing this one -- see issue #9 which describes the `suggest` element to handle enums (both inline and URL-accessible).
