### ISSUE TITLE
minLength/maxLength question

### ISSUE THREAD

**Issue by evert** [mamund/hal-forms#54]
From the current draft (in the minLength chapter)

> this attribute SHOULD appear along with the maxLength attribute

I'm not sure why minLength should appear when maxLength does and vice versa. I think there's legitimate reasons for each to appear without the other.

**Comment by mamund** [comment]
SHOULD is not MUST. Bu maybe you would prefer MAY? 

Do you think the same is true for `min` and `max`?

**Comment by evert** [comment]
`MAY` makes a lot more sense to me =) `SHOULD` to me is 'really ought to but not strictly required'. Indeed similar to min/max.

**Comment by mamund** [comment]
MAY works for me.  I'll update and commit the change in the next round of mods.  Thanks.

**Comment by mamund** [comment]
resolved
